import axios from 'axios'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import NoResults from '../components/NoResults';
import VideoCard from '../components/VideoCard';
import { Video } from '../types';

interface Iprops{
  videos: Video[];
}

const Home = ({videos}:Iprops) => {
  console.log(videos);
  
  return (
    <div className='text-3xl text-red-400' >
      <Head>
        <title>KPMEDIA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='flex flex-col gap-10 videos h-full'>
      {videos.length 
        ? videos?.map((video: Video) => (
          <VideoCard post={video} isShowingOnHome key={video._id} />
        )) 
        : <NoResults text={`No Videos`} />}
    </div>
     
    </div>
  )
}
export const getServerSideProps = async () =>{
  const {data}  = await axios.get(`http://localhost:3000/api/post`);
  
  return {
    props:{
      videos:data
    }
  }

}
export default Home
